apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylladb
  labels:
    app: scylladb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scylladb
  template:
    metadata:
      labels:
        app: scylladb
    spec:
      containers:
      - name: scylladb
        image: scylladb/scylla:latest
        ports:
        - containerPort: 9042
        env:
        - name: SCYLLA_CLUSTER_NAME
          value: "local-cluster"
        - name: SCYLLA_DC
          value: "dc1"
        - name: SCYLLA_RACK
          value: "rack1"
        volumeMounts:
        - name: scylladb-data
          mountPath: /var/lib/scylla
      volumes:
      - name: scylladb-data
        emptyDir: {}
